apiVersion: secrets.hashicorp.com/v1beta1
kind: CSISecrets
metadata:
  name: vault-kv-app
  namespace: app-1
spec: 
  vaultAuthRef:
    name: static-auth
  secrets: 
    vaultStaticSecrets:
    - mount: secret
      path: team-a/my-app/test
      type: kv-v2
  accessControl:
    serviceAccountPattern: "my-app"
    namespacePatterns:
    - "app-1"
    podNamePatterns:
    - "^my-app-"
  syncConfig:
    containerState: 
      namePattern: "^(app|sidecar)$"
